import React from "react";

export const proyectos = [
  {
    name: "Good Seeds",
    business: "Recursiva",
  },
];
export const skills = [
  {
    name: "React",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: true,
    src: require("../assets/react-icon.svg").default,
    companies: ["eon6", "Fichap"],
  },
  {
    name: "React Native",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: true,
    src: require("../assets/react-icon.svg").default,
    companies: ["eon6"],
  },
  {
    name: "Angular",
    level: "Advanced",
    recognition: true,
    recognitionText: "Reconocimiento de Tech Leader - Proyect Leader",
    wantToWork: false,
    src: require("../assets/angular-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "HTML",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/html-icon.svg").default,
    companies: [],
  },
  {
    name: "Javascript",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/javascript-icon.svg").default,
    companies: [],
  },
  {
    name: "CSS",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/css-icon.svg").default,
    companies: [],
  },
  {
    name: "Next.JS",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/next-js-icon.svg").default,
    companies: ["Fichap"],
  },
  {
    name: "Node.JS",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/nodejs-icon.svg").default,
    companies: ["eon6"],
  },
  {
    name: "MySQL",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/mysql-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "Postman",
    level: "Tools",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/postman-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "Git",
    level: "Tools",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/git-icon.svg").default,
    companies: ["eon6", "Recursiva", "Fichap"],
  },
  {
    name: "MongoDB",
    level: "Basic",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/mongodb-icon.svg").default,
    companies: [],
  },
  {
    name: ".Net Core",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/net-icon.svg").default,
    companies: ["Recursiva"],
  },
];

export const skillTypes = ["Global", "Advanced", "Middle", "Basic"];

export const experiences = [
  {
    company: "Recursiva",
    position: "Software Developer",
    description:
      "Software Factory. Soluciones combinando una fuerte vocación de servicio con una búsqueda permanente por la innovación tecnológica.\n Trabajo en equipo de desarrollo con diseñadores, QA testers, desarrolladores y proyect leader.",
    startDate: "Abril/2022",
    endDate: "Actualidad",
    img: "",
    logo: require("../assets/logo-recu.png"),
  },
  {
    company: "eon6",
    position: "Software Developer Junior",
    description:
      "Startup. Desarrollo de distintas aplicaciones web y mobile. Trabajo en equipo e individual. Desarrollo de tecnologías en frontend y backend. Documentación de Tareas. Estimación de tiempos.",
    startDate: "Julio/2021",
    endDate: "Abril/2022",
    img: "",
    logo: require("../assets/Eon6-logo.png"),
  },
  {
    company: "Fichap",
    position: "Frontend Software Developer Freelance",
    description:
      "Desarrollo de nuevas funcionalidades, corrección de errores y nuevos requerimientos. Trabajo de forma individual con reuniones semanales de Avances y documentación de tareas.",
    startDate: "Noviembre/2021",
    endDate: "Enero/2022",
    img: "",
    logo: require("../assets/fichap-logo.svg").default,
  },
];
