import React from "react";

export const proyectos = [
  {
    name: "Good Seeds",
    logo: require("../assets/logo-goodseed.svg").default,
    company: "Recursiva",
    repository: "",
    url: "https://explore-pl-frontend-stg.azurewebsites.net/login",
    description:
      "Progressive Web App - Aplicación para administrar y analizar semillas de Soja y Maiz. Material UI con dificultad media/alta. Router Angular. RXJS.",
    dateFrom: "04/2022",
    dateTo: "",
    proyectUrl: "",
    activities: [
      "Api Rest",
      "Manejo de filtros",
      "Tablas multifuncionales",
      "Subscriber/Observer/Events RxJs.",
      "Transiciones",
      "Formularios",
      "Mejoras performance",
      "Importación/exportación de .xlsx",
      "Manejo Database",
      "Scripts",
      "Servicios",
    ],
    tecnologies: ["Git", ".Net Core", "Angular", "CSS", "MySQL", "Postman"],
  },
  {
    name: "Fichap Web",
    logo: require("../assets/fichap-logo.svg").default,
    company: "Fichap",
    repository: "",
    url: "https://fichap.com",
    description:
      "Landing Page. Corrección de bugs, mantenimiento, nuevas funcionalidades y requerimientos. Creación de formularios.",
    dateFrom: "11/2021",
    dateTo: "01/2022",
    proyectUrl: "",
    activities: [
      "Formularios",
      "Transiciones",
      "Maquetación",
      "Transiciones SVG",
      "Responsive Design",
    ],
    tecnologies: ["Git", "Next.JS", "React"],
  },
  {
    name: "eon6 Panel Admin",
    logo: require("../assets/Eon6-logo.png"),
    company: "eon6",
    repository: "",
    url: "",
    description:
      "Desarrollo desde 0 de panel admin para organizar la infraestructura de la startup. Material UI y creación d e Api y backend",
    dateFrom: "10/2021",
    dateTo: "04/2022",
    proyectUrl: "",
    activities: [
      "Tablas multifuncionales",
      "Endpoints",
      "Manejo Base de datos",
      "Login/Logout",
      "Servicios",
    ],
    tecnologies: ["Git"],
  },
  {
    name: "La Corriente",
    logo: require("../assets/la-corriente.png"),
    company: "eon6",
    repository: "",
    url: "https://play.google.com/store/apps/details?id=com.eon6.lacorriente",
    description:
      "App Mobile IOS/Android en Angular Ionic. Modificación de perfiles, foro online, comentarios, creación de thread. ",
    dateFrom: "09/2021",
    dateTo: "04/2022",
    proyectUrl: "",
    activities: ["Creación de threads", "Formularios", "Endpoints"],
    tecnologies: ["Git", "Angular", "Node.JS", "MySQL"],
  },
  {
    name: "Prometeo ERP",
    logo: require("../assets/logo-prometeo.svg").default,
    company: "eon6",
    repository: "",
    url: "",
    description:
      "Panel de administración de Empresa Fumigadora. Formularios de alto nivel. Creación de ordenes, manejo de Rutas, dashborad",
    dateFrom: "01/2022",
    dateTo: "04/2022",
    proyectUrl: "",
    activities: ["Formularios", "Order data", "Servicios"],
    tecnologies: ["Git", "Angular"],
  },
  {
    name: "Gulf App",
    logo: require("../assets/gulf.jpg"),
    company: "eon6",
    repository: "",
    url: "https://play.google.com/store/apps/details?id=com.p97.gulf&hl=es_AR&gl=US",
    description:
      "Maquetacion de pantallas de App Mobile de venta de combustibles. React Native + Expo",
    dateFrom: "02/2022",
    dateTo: "04/2022",
    proyectUrl: "",
    activities: ["Maquetación de pantallas", "Formularios"],
    tecnologies: ["Git"],
  },
];
export const skills = [
  {
    name: "React",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: true,
    src: require("../assets/react-icon.svg").default,
    companies: ["eon6", "Fichap"],
  },
  {
    name: "React Native",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: true,
    src: require("../assets/react-icon.svg").default,
    companies: ["eon6"],
  },
  {
    name: "Angular",
    level: "Advanced",
    recognition: true,
    recognitionText: "Reconocimiento de Tech Leader - Proyect Leader",
    wantToWork: false,
    src: require("../assets/angular-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "HTML",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/html-icon.svg").default,
    companies: [],
  },
  {
    name: "Javascript",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/javascript-icon.svg").default,
    companies: [],
  },
  {
    name: "CSS",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/css-icon.svg").default,
    companies: [],
  },
  {
    name: "Next.JS",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/next-js-icon.svg").default,
    companies: ["Fichap"],
  },
  {
    name: "Node.JS",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/nodejs-icon.svg").default,
    companies: ["eon6"],
  },
  {
    name: "MySQL",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/mysql-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "Postman",
    level: "Tools",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/postman-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "Git",
    level: "Tools",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/git-icon.svg").default,
    companies: ["eon6", "Recursiva", "Fichap"],
  },
  {
    name: "MongoDB",
    level: "Basic",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/mongodb-icon.svg").default,
    companies: [],
  },
  {
    name: ".Net Core",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/net-icon.svg").default,
    companies: ["Recursiva"],
  },
];

export const skillTypes = ["Global", "Advanced", "Middle", "Basic"];

export const experiences = [
  {
    company: "Recursiva",
    position: "Software Developer",
    description:
      "Software Factory. Soluciones combinando una fuerte vocación de servicio con una búsqueda permanente por la innovación tecnológica.\n Trabajo en equipo de desarrollo con diseñadores, QA testers, desarrolladores y proyect leader.",
    startDate: "Abril/2022",
    endDate: "Actualidad",
    img: "",
    logo: require("../assets/logo-recu.png"),
  },
  {
    company: "eon6",
    position: "Software Developer Junior",
    description:
      "Startup. Desarrollo de distintas aplicaciones web y mobile. Trabajo en equipo e individual. Desarrollo de tecnologías en frontend y backend. Documentación de Tareas. Estimación de tiempos.",
    startDate: "Julio/2021",
    endDate: "Abril/2022",
    img: "",
    logo: require("../assets/Eon6-logo.png"),
  },
  {
    company: "Fichap",
    position: "Frontend Software Developer Freelance",
    description:
      "Desarrollo de nuevas funcionalidades, corrección de errores y nuevos requerimientos. Trabajo de forma individual con reuniones semanales de Avances y documentación de tareas.",
    startDate: "Noviembre/2021",
    endDate: "Enero/2022",
    img: "",
    logo: require("../assets/fichap-logo.svg").default,
  },
];
