import React from "react";

export const proyectos = [
  {
    name: "Good Seeds",
    jobTitle: "Fullstack developer",
    id: "good-seed",
    type: "web",
    logo: require("../assets/logo-goodseed.svg").default,
    company: "Recursiva",
    repository: "",
    url: "https://explore-pl-frontend-stg.azurewebsites.net/login",
    description:
      "Progressive Web App - Aplicación para administrar y analizar semillas de Soja y Maiz. Es gran proyecto para una empresa multinacional. Gracias al trabajo en equipo de 8-10 personas salió un proyecto increíble.",
    dateFrom: "04/2022",
    dateTo: "11/2022",
    testimonios: [],
    proyectUrl: "",
    demos: [require("../assets/demos/notes.webm")],
    images: [
      require("../assets/proyects/CYM.jpg"),
      require("../assets/proyects/notes.jpg"),
    ],
    activities: [
      "Api Rest",
      "Manejo de filtros",
      "Tablas multifuncionales",
      "Subscriber/Observer/Events RxJs.",
      "Transiciones",
      "Formularios",
      "Mejoras performance",
      "Importación/exportación de .xlsx",
      "Manejo Database",
      "Scripts",
      "Servicios",
    ],
    tecnologies: ["Git", ".Net Core", "Angular", "CSS", "MySQL", "Postman"],
  },
  {
    name: "Agroapp",
    jobTitle: "Fullstack developer mobile",
    id: "agroapp",
    type: "mobile",
    logo: require("../assets/agroapp-logo1.png"),
    company: "Recursiva",
    repository: "",
    url: "https://play.google.com/store/apps/details?id=com.bereco.agroapp",
    description:
      "AgroApp te permite planificar tus aplicaciones de fitosanitarios gracias a un pronóstico del clima mejorado con una red de datos medidos en tiempo real.",
    dateFrom: "11/2022",
    dateTo: "",
    testimonios: [],
    proyectUrl: "",
    demos: [],
    images: [
      require("../assets/proyects/agroapp1.jpeg"),
      require("../assets/proyects/agroapp.jpeg"),
    ],
    activities: [
      "Servicios",
      "Google maps API",
      "Api",
      "Formularios",
      "Manejo de database",
      "Despliegue en Android/Ios",
      "Despliegue backend via FileZilla",
    ],
    tecnologies: ["Git", "Ionic Angular", "PHP", "Cordova"],
  },
  {
    name: "Novedades App",
    jobTitle: "Backend developer",
    id: "novedades-app",
    type: "servidor",
    logo: null,
    company: "Recursiva",
    repository: "",
    url: "",
    description:
      "App de Notificaciones push para productos de distintos laboratorios de Sudamérica. Creación de modelo de datos, API, Microservicios. .NetCore EF",
    dateFrom: "01/2023",
    dateTo: "",
    testimonios: [],
    proyectUrl: "",
    demos: [],
    images: [],
    activities: ["Modelado de datos", "Api", "Administración de database"],
    tecnologies: ["Git", ".Net Core", "Entity Framework", "React Native"],
  },
  {
    name: "Fichap Web",
    jobTitle: "Frontend developer",
    id: "fichap-web",
    type: "web",
    logo: require("../assets/fichap-logo.svg").default,
    company: "Fichap",
    repository: "",
    url: "https://fichap.com",
    description:
      "Landing Page. Corrección de bugs, mantenimiento, nuevas funcionalidades y requerimientos. Creación de formularios.",
    dateFrom: "11/2021",
    dateTo: "01/2022",
    testimonios: [],
    proyectUrl: "",
    demos: [],
    images: [
      require("../assets/proyects/fichap.jpg"),
      require("../assets/proyects/fichap1.jpg"),
    ],
    activities: [
      "Formularios",
      "Transiciones",
      "Maquetación",
      "Transiciones SVG",
      "Responsive Design",
    ],
    tecnologies: ["Git", "Next.JS", "React"],
  },
  {
    name: "eon6 Panel Admin",
    jobTitle: "Fullstack developer",
    id: "eon6-panel-admin",
    type: "web",
    logo: require("../assets/Eon6-logo.png"),
    company: "eon6",
    repository: "",
    url: "",
    description:
      "Desarrollo desde 0 de panel admin para organizar la infraestructura de la startup. Material UI y creación d e Api y backend",
    dateFrom: "10/2021",
    dateTo: "04/2022",
    testimonios: [],
    proyectUrl: "",
    demos: [],
    images: [
      require("../assets/proyects/eon6-panel-admin.jpg"),
      require("../assets/proyects/eon6-panel-admin1.jpg"),
    ],
    activities: [
      "Tablas multifuncionales",
      "Endpoints",
      "Manejo Base de datos",
      "Login/Logout",
      "Servicios",
    ],
    tecnologies: ["Git", "React", "Node.Js"],
  },
  {
    name: "La Corriente",
    jobTitle: "Fullstack developer mobile",
    id: "la-corriente",
    type: "mobile",
    logo: require("../assets/la-corriente.png"),
    company: "eon6",
    repository: "",
    url: "https://play.google.com/store/apps/details?id=com.eon6.lacorriente",
    description:
      "App Mobile IOS/Android en Ionic Angular. Modificación de perfiles, foro online, comentarios, creación de thread. ",
    dateFrom: "09/2021",
    dateTo: "04/2022",
    testimonios: [],
    proyectUrl: "",
    demos: [],
    images: [
      require("../assets/proyects/la-corriente.jpeg"),
      require("../assets/proyects/la-corriente1.jpeg"),
    ],
    activities: ["Creación de threads", "Formularios", "Endpoints"],
    tecnologies: ["Git", "Angular", "Node.JS", "MySQL"],
  },
  {
    name: "Prometeo ERP",
    jobTitle: "Frontend developer",
    id: "prometeo-erp",
    type: "web",
    logo: require("../assets/logo-prometeo.svg").default,
    company: "eon6",
    repository: "",
    url: "",
    description:
      "Panel de administración de Empresa Fumigadora. Formularios de alto nivel. Creación de ordenes, manejo de Rutas, dashborad",
    dateFrom: "01/2022",
    dateTo: "04/2022",
    testimonios: [],
    proyectUrl: "",
    demos: [],
    images: [
      require("../assets/proyects/prometeo.jpg"),
      require("../assets/proyects/prometeo1.jpg"),
    ],
    activities: ["Formularios", "Order data", "Servicios"],
    tecnologies: ["Git", "Angular", ".Net core"],
  },
  {
    name: "Gulf App",
    jobTitle: "Frontend developer",
    id: "gulf-app",
    type: "mobile",
    logo: require("../assets/gulf.jpg"),
    company: "eon6",
    repository: "",
    url: "https://play.google.com/store/apps/details?id=com.p97.gulf&hl=es_AR&gl=US",
    description:
      "Maquetacion de pantallas de App Mobile de venta de combustibles. React Native + Expo",
    dateFrom: "02/2022",
    dateTo: "04/2022",
    testimonios: [],
    proyectUrl: "",
    demos: [],
    images: [
      require("../assets/proyects/gulf.jpeg"),
      require("../assets/proyects/gulf1.jpeg"),
    ],
    activities: ["Maquetación de pantallas", "Formularios"],
    tecnologies: ["Git", "React Native"],
  },
];
export const skills = [
  {
    name: "React",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: true,
    src: require("../assets/react-icon.svg").default,
    companies: ["eon6", "Fichap"],
  },
  {
    name: "React Native",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: true,
    src: require("../assets/react-icon.svg").default,
    companies: ["eon6"],
  },
  {
    name: "Angular",
    level: "Advanced",
    recognition: true,
    recognitionText: "Reconocimiento de Tech Leader - Proyect Leader",
    wantToWork: false,
    src: require("../assets/angular-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "HTML",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/html-icon.svg").default,
    companies: [],
  },
  {
    name: "Javascript",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/javascript-icon.svg").default,
    companies: [],
  },
  {
    name: "CSS",
    level: "Global",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/css-icon.svg").default,
    companies: [],
  },
  {
    name: "Next.JS",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/next-js-icon.svg").default,
    companies: ["Fichap"],
  },
  {
    name: "Node.JS",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/nodejs-icon.svg").default,
    companies: ["eon6"],
  },
  {
    name: "MySQL",
    level: "Advanced",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/mysql-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "Postman",
    level: "Tools",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/postman-icon.svg").default,
    companies: ["eon6", "Recursiva"],
  },
  {
    name: "Git",
    level: "Tools",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/git-icon.svg").default,
    companies: ["eon6", "Recursiva", "Fichap"],
  },
  {
    name: "MongoDB",
    level: "Basic",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/mongodb-icon.svg").default,
    companies: [],
  },
  {
    name: ".Net Core",
    level: "Middle",
    recognition: false,
    recognitionText: "",
    wantToWork: false,
    src: require("../assets/net-icon.svg").default,
    companies: ["Recursiva"],
  },
];

export const skillTypes = ["Global", "Advanced", "Middle", "Basic"];

export const experiences = [
  {
    company: "Recursiva",
    position: "Software Developer",
    description:
      "Software Factory. Soluciones combinando una fuerte vocación de servicio con una búsqueda permanente por la innovación tecnológica.\n Trabajo en equipo de desarrollo con diseñadores, QA testers, desarrolladores y proyect leader.",
    startDate: "Abril/2022",
    endDate: "Actualidad",
    img: "",
    logo: require("../assets/logo-recu.png"),
  },
  {
    company: "eon6",
    position: "Software Developer Junior",
    description:
      "Startup. Desarrollo de distintas aplicaciones web y mobile. Trabajo en equipo e individual. Desarrollo de tecnologías en frontend y backend. Documentación de Tareas. Estimación de tiempos.",
    startDate: "Julio/2021",
    endDate: "Abril/2022",
    img: "",
    logo: require("../assets/Eon6-logo.png"),
  },
  {
    company: "Fichap",
    position: "Frontend Software Developer Freelance",
    description:
      "Desarrollo de nuevas funcionalidades, corrección de errores y nuevos requerimientos. Trabajo de forma individual con reuniones semanales de Avances y documentación de tareas.",
    startDate: "Noviembre/2021",
    endDate: "Enero/2022",
    img: "",
    logo: require("../assets/fichap-logo.svg").default,
  },
];
